# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\selectionwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectionWindow(object):
    def setupUi(self, selectionWindow):
        selectionWindow.setObjectName("selectionWindow")
        selectionWindow.setWindowModality(QtCore.Qt.NonModal)
        selectionWindow.resize(340, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(selectionWindow.sizePolicy().hasHeightForWidth())
        selectionWindow.setSizePolicy(sizePolicy)
        selectionWindow.setMinimumSize(QtCore.QSize(340, 700))
        selectionWindow.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(selectionWindow)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(selectionWindow)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 460))
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget.setIndentation(5)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout.addWidget(self.treeWidget)
        self.line = QtWidgets.QFrame(selectionWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.buttonBox = QtWidgets.QDialogButtonBox(selectionWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(selectionWindow)
        self.buttonBox.accepted.connect(selectionWindow.accept)
        self.buttonBox.rejected.connect(selectionWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(selectionWindow)

    def retranslateUi(self, selectionWindow):
        _translate = QtCore.QCoreApplication.translate
        selectionWindow.setWindowTitle(_translate("selectionWindow", "Dialog"))
        self.treeWidget.headerItem().setText(0, _translate("selectionWindow", "Schauspieler"))
