DROP TABLE IF EXISTS "actors";
CREATE TABLE "actors" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "prename" VARCHAR, "name" VARCHAR NOT NULL);
DROP TABLE IF EXISTS "cast";
CREATE TABLE "cast" ("actor_id" INTEGER NOT NULL , "movie_id" INTEGER NOT NULL , PRIMARY KEY ("actor_id", "movie_id"));
DROP TABLE IF EXISTS "category";
CREATE TABLE "category" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "name" VARCHAR NOT NULL  UNIQUE );
DROP TABLE IF EXISTS "movies";
CREATE TABLE "movies" (
[id] INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL,
[titel] VARCHAR(250)  NULL,
[laenge] INTEGER  NULL,
[medien] INTEGER  NULL,
[usk] INTEGER  NULL,
[preis] FLOAT  NULL
, "type_id" INTEGER);
DROP TABLE IF EXISTS "tags";
CREATE TABLE "tags" ("movie_id" INTEGER NOT NULL , "category_id" INTEGER NOT NULL , PRIMARY KEY ("movie_id", "category_id"));
DROP TABLE IF EXISTS "type";
CREATE TABLE "type" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "name" VARCHAR NOT NULL );
INSERT INTO "type" VALUES(1,'DVD');
INSERT INTO "type" VALUES(2,'Bluray');